---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3-server
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
     app: iperf3-server
  template:
    metadata:
      labels:
        app: iperf3-server
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - debug-pod
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: iperf3-server
        image: networkstatic/iperf3
        args:
          - -s
        ports:
        - containerPort: 5201
          protocol: TCP
